version: "3.2"
services:
    server:
      restart: always
      image: server
      build: './server'
      command : bash -c "python manage.py makemigrations &&
                        python manage.py migrate &&
                        python manage.py runserver 0.0.0.0:8000"

      ports:
        - "8000:8000"
      # depends_on:
      #   - db
      #   - redis
      # networks:
      #   - db-net
      volumes:
        - ./server/:/tf